travis:
  secure:
    BINSTAR_TOKEN: ffri+HG7h97G7eb8SUDVy2X7mNHMYS+G8g5KqipHko2HHlQmCqee/7/lorgKIPpBvvS3SudKJY+M03nzAaObmhm7LE4Uj6ygqOSHF4coN8PIMU6zKx78lLAjFTQ/iYJ9r/GBy85oz21RJIw3yrKj3540CSzG3N3kbFnh8VYvt1V+qmSZpDUCDOqD7MVi0hgnDF17RtyRTRQNjxCMdUf+EOKClip++D9LdIsPscxDJipb4GpOa7e8vb+6TZ1WJcQbmMHxszBF6IDoW3yWNrm2VD1rX2M6u7dy9ts03KX0xG8l3ZfhJ/MQ8tGCxn2y9bPnrlXDsLXxMJwebZtjHFs2mdEJQYkSTqw9CDrq4r0ktHueP6BLfi9l1YnSWsu8gDqca2igJirjxo2ZYN2nLEowntTnN7Tn1nsfPfXp2hxO5Q/ootulrZtAypbo/OSmkn2KHxspJOBM+98unK5hwjSpaElrMc5hfsLsKJfjVwHCcRc+d/a9Tt3ul/N9JUWsz2dh4cz7mQ3zlO2el5mk+ehBZHTzPoguOXa+gl4tn4szUk0YhLBWMK2dpCYm/UhJvZgHO7E35P75mbWo4ZRqItMtbmudqLDA+/4G9awbWLdrzp498r6j8bLGEwZqlhspYr9i8qy+Zb1IAbNy+BuOGSV+hUB5GcHrP72LJqQB+2WUPqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
