travis:
  secure:
    BINSTAR_TOKEN: Sz9fohkR1oMv/Z76Y+/M3PHYusq9qbUwgfCY55A423uzHQ80yTkebg8YtF1XchugOct2xwCqKgrEo+/UbwpWR1UWaQY00ZZxk/EIwP0NRr2NRW1oQmeEzNEShzJrtj9AjTOaW3TPXLzxQvpJBN6gwQ42fvkWXQyIaQ2fKGXI61BaekGii3e9M0Gb5o1B4IebfpG8H72qZCHIu0Am68rkyg16we5jM6NTjpezT22U7o66I2U+EeMiE/i9tUjh8wRnGerVLjNBVETQbCgI6BiqccNEmPK98YZIi1pq1+mlhbQ/rYlJ0YY7AsCqeEdsvj0CLxXAPpDCevHmiLNyS/Q50YNyS15TrYRFL77A5F8zSqcAVdgRl390sQ/L7W9tA5tg83+qJsooer3Vj9M3foVZFLa0sDyzY0z74FLCsL3mHDx2IUqEZmRoKJmyD9VlN5nq+HwZHtBuhhhrnsqbJztn4Ql4/QVsanq/OAG1k6tCu9cNv+GV5xhKCKJ4wIpf14xwsU/tmYI8oZPiXQ2LnapsnERSIjfY/n95rjTANVsunJsqJtHuHjf9otSIqNF7MuhUtdcecL4PEKfa0t95RXQaadfr6mRXE3UejTcefQ6XBSJuxCMzlxIWdH4d3tw71ACqkAgd8zbOgvmm4R0L5DKu35XOeDPdU7/IkJOJJ7fb7RY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
