travis:
  secure:
    BINSTAR_TOKEN: Tibo7BYVXPEFkUJzhI8dY58J3h0Eco/DNGjwaT4m/+jlG59V7EpYgZkDIZh31LdoPS5apUM4qtLGxjEwFhXm420bi7t1PTjggZQUDtF+vYAfHWexJYIPaj7sezpCo/LpUyztIhzJzyFNzbjl4dp0wW3nqjeqDGPI5eGMQshcADmHozQKZ6S+4+LkDGJDUNjRayg7+u/TrztMDYSTYcGjXdHNEPW86Sy9YomtFXCBa1S/TyRXN5+zTr1NuE2+82A58cUzQ8KAalYvYI73ipg0n/NwlRREeRVRBzcvlPRRtD3IL52CCCkjAEJM9sVJKmDWyU3HVCFYYqmQJFyWI789lVoVeGkDdyH2+Q6fKay4f0yQGluE669pmy0DHGMDbvQnYLmuTGx4oEWDvabwDzlwzxRniFyviGl6feLHr10U/00S1GNqnRc6EQm6SX8/OIcOBGva2/7bNEW5lImu8oo2SCOtuVWcbdUzmStyMDdeBtBJkDhE7mA197yGktzGfvrFRPcluxOFgd4rCuzXCo7jjh57Us6s+SFJq+XtoS8/YnnR6MCrQEnGB+1ci5U/sO5yjb+B8nPy2QSvA/3aYYeXTJxrk82zjtjKByDqYZmhFulASBw9eTGj5XuhzuXsVyacVikcpLkucUD8qo55bZjO85cwMEkmob7J0zjlXkUOwFk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
